#!/usr/bin/env node
/**
 * scripts/build-embed.mjs — Inlines public/index.html and themes/*.json into
 * lib/embedded-assets.mjs so a compiled executable carries everything in one
 * file. The generated module is gitignored and deleted after the build.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..')
const OUT = path.join(ROOT, 'lib', 'embedded-assets.mjs')

const indexHtml = fs.readFileSync(path.join(ROOT, 'public', 'index.html'), 'utf8')

const themes = []
for (const file of fs.readdirSync(path.join(ROOT, 'themes'))) {
  if (!file.endsWith('.json')) continue
  const theme = JSON.parse(fs.readFileSync(path.join(ROOT, 'themes', file), 'utf8'))
  if (theme && theme.id && theme.colors) themes.push(theme)
}
themes.sort((a, b) => (a.id < b.id ? -1 : 1))

const source = [
  '// Generated by scripts/build-embed.mjs — do not edit by hand.',
  `export const indexHtml = ${JSON.stringify(indexHtml)};`,
  `export const themes = ${JSON.stringify(themes, null, 2)};`,
  '',
].join('\n')

fs.writeFileSync(OUT, source)
console.log(`[build] embedded ${themes.length} theme(s) and index.html (${(source.length / 1024).toFixed(1)} kB) -> ${path.relative(ROOT, OUT)}`)
